### ISSUE TITLE
Healthchecks 'success' not sent when borg returns 1 (which is only a warning)

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/emborg#55]
If borg completes with a warning (say a file disappeared during the backup, so could not be processed) it appears that the healthcheck 'finished' ping isn't sent.

Borg's return codes are documented here:

https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes

It looks like the 'success' ping is only sent if borg returns zero:

https://github.com/KenKundert/emborg/blob/87d1624bf6b2c2d03602c80eafe1d1e2446f23bc/emborg/hooks.py#L60-L66

**Comment by KenKundert** [comment]
Okay, I think this is fixed and checked in to GitHub.  Give it a try and let me know whether it meets your expectations.

Thanks!

**Comment by adhawkins** [comment]
The code change looks good, but I'll have to see if I can engineer a test for this, as I don't get these '1' return codes very often.

**Comment by KenKundert** [comment]
I had the same concern, but then accidentally stumbled on the answer minutes before starting to work on this.  Simply create a file in the directory to be backed up and make it unreadable (chmod 000). Then run the backup.

**Comment by adhawkins** [comment]
Sadly, that doesn't help when emborg is being run as root (as it is in my docker container).

When you make a release containing this fix, I'll package it up for alpine and start using it, then monitor for any future occurrence.

**Comment by adhawkins** [comment]
Update, I inadvertantly re-created it by deleting the file I'd created before the backup had got round to actually processing it. My healthchecks still shows that backup job as having started but not completed, which suggests no 'finished' ping was sent.

**Comment by adhawkins** [comment]
Done some digging, and it seems that if borg exits with status '1', then this causes the [exception handler](https://github.com/KenKundert/emborg/blob/8ebb4a928280a3670197ba7bfc0ea9d19deca2a4/emborg/command.py#L646-L650) to be triggered. 

This just raises the exception up the chain, meaning that none of the 'end of backup' stuff is run. I suspect this also occurs if there's a 'real' error, meaning the healthchecks 'fail' event will never be signalled.

**Comment by KenKundert** [comment]
Whoops, I missed one case, the case where narrate is set.  I have fixed and uploaded the new version to GitHub.  The problem was not with the exception handling, rather run_borg() should have been modified so that it did not raise an exception when the Borg exit status was 1.  That was only partially done with the first version. Hopefully this new version works as expected.

It may take me a while to promote this version to PyPi.  I was unaware of Borg's exit status policy, but now that I know about it I think Emborg should adhere to the same policy.  So I will take some time to implement changes to Emborg's exit status.  Once that is done and documented I will promote this new version to PyPi.

**Comment by adhawkins** [comment]
Ok, that now does seem to send the completed ping to healthchecks. However, I see you're now sending the status, and healthchecks treats a status of 1 as a failure, triggering an email to that effect.

Would probably be better to only send a status if the status is >1, otherwise send a successful completion?

**Comment by KenKundert** [comment]
Sorry, I don't really use healthchecks, so I did not notice this detail.  I have updated Emborg again.  I have fixed your most recent issue and changed the behavior of emborg's exit status to match that of borg.

**Comment by adhawkins** [comment]
Ok, all looks good, both with and without -v.

Will keep an eye out for an official release, and update the Alpine package when I see it.

**Comment by KenKundert** [comment]
Thanks Andy, should be a couple of days.  Let me know if you see anything unusual.

**Comment by KenKundert** [comment]
I have released the updated version to PyPi.

Thanks again!
